[workspace]
name = "megaevent"
version = "1.0.0"
channels = ["conda-forge"]
platforms = [{platform = "linux-64", cuda="12"}, {platform = "win-64", cuda="12"}, {platform = "osx-arm64"}]

[dependencies]
python = "<=3.12"
eventcv = "*"
tensorboard = "*"
wandb = "*"
pytest = "*"
h5py = "*"
ruff = "*"
tqdm = "*"
loguru = "*"
huggingface_hub = "*"
torchvision = "*"
pandas = "*"
pytorch-metric-learning = "*"

[target.linux-64.dependencies]
cuda-version = "12.*"
mkl = "<2026"
pytorch-gpu = "*"
cuda-cudart-dev = "*"
cuda-crt = "*"
cudnn = "*"
libcusparse-dev = "*"
cuda-driver-dev = "*"
cuda-nvcc = "*"
cuda-nvrtc-dev = "*"
cuda-nvtx-dev = "*"
cuda-nvml-dev = "*"
cuda-profiler-api = "*"
cusparselt = "*"
libcublas-dev = "*"
libcudss-dev = "*"
libcufile-dev = "*"
libcufft-dev = "*"
libcurand-dev = "*"
libcusolver-dev = "*"
safetensors = "*"

[target.win-64.dependencies]
pytorch-gpu = "*"

[target.osx-arm64.dependencies]
pytorch = "*"

[tasks]
megaevent = { cmd = "python -m megaevent", env = { PYTHONPATH = "src" } }
test = "pytest"
